<!-- HEAD INCLUDE FILE -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
<meta name="description" content="">


<!-- STYLESHEETS -->
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
<link rel="stylesheet" type="text/css" href="Stylesheets/purecss_custom.css">
<link rel="stylesheet" type="text/css" href="Stylesheets/custom-style.css">
<script src="../../learning-module/js/ext/jquery-2.2.0.js"></script>

<?php
	// require_once 'navigationmenu.inc';
	require_once 'core/init.php';
	require_once 'classes/DB.php';
	require_once 'Includes/birdfunctions.inc';
	require_once 'Includes/navmenu.inc';
?>
