<!-- Navigation menu for use across site -->

<nav class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
  <a href="index.php" class="pure-menu-heading">B<sup>4</sup></a>
  <ul class="pure-menu-list">
        <li class="pure-menu-item"><a href="brisbanebirds.php" class="pure-menu-link">Administrate</a></li>
        <li class="pure-menu-item pure-menu-item-alternate"><a href="" class="pure-menu-link">Record</a></li>
        <li class="pure-menu-item"><a href="../../learning-module/" class="pure-menu-link">Learn</a></li>
        <li class="pure-menu-item pure-menu-item-alternate"><a href="#" class="pure-menu-link">About</a></li>
    </ul>
</nav>

<!-- <img src="../../learning-module-assets/favicon.png">  -->